# Generated by Django 3.2.2 on 2021-05-11 05:56

import accounts.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210511_1024'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', accounts.manager.UserManager()),
            ],
        ),
    ]
